### PR TITLE
RTAPI-7 - Merged the accounts table and users table together into jus…

### PR DESCRIPTION
**Pull request by cpb2948**
…t the users table. Update code accordingly

### CODE REVIEW

**Comment by cpb2948** [comment]
@dadleyy Just did what we talked about, merging the users and accounts table together, and updated the code appropriately.

**Comment by dadleyy** [comment]
cool :shipit:

**Comment by dadleyy** [comment]
you forgot the square brackets on your commit message though -

`[RTAPI-7] merged the account and user tables`

**Comment by dadleyy** [comment]
also, it looks like you need to run some [git config commands](https://help.github.com/articles/setting-your-email-in-git/) in your shell:

```
$ git config --global user.email "your_email@example.com"
$ git config --global user.name "Cory Baker"
```

this will make it so your commit messages have your username on github

**Comment by dadleyy** [comment]
do we have a route for logging users in? I was expecting to see a 

```
POST /auth
```

**Comment by cpb2948** [comment]
All that information i documented as best as i could on that google doc

https://docs.google.com/document/d/1IL6q4TNU74i1HZ6O6N_3ltgRWrjgRi8_RwLVW1z6Do8/edit

**Pull request merged**
