### PR TITLE
[RTAPI-6] - Implemented the registration functionality. Also included …

### PR DESCRIPTION
**Pull request by cpb2948**
…a global exception handlers that returns json. To be used only in production.

### CODE REVIEW

**Comment by cpb2948** [comment]
Sorry if some of this is off. I haven't use git before

**Comment by dadleyy** [comment]
lol dont bother with "assigning" it to people. just `@` me and I'll look at it.

I'm still not convinced why the `account` and `user` data models should be separate. what's your thinking there?

**Comment by dadleyy** [comment]
good job with the commit message though. thats what i'm looking for.

**Comment by cpb2948** [comment]
The reason i broke it up was to differentiate the site specific information and auth, such as a username and password from the real life information such as firstname lastname etc. If down the line we implement like user roles such as an admin or whatever or we decide we want to try "sign in using facebook" a real person may have multiple accounts. Also if we add more information such as state, zip, street it just prevents the table from getting massive.

**Comment by dadleyy** [comment]
I still think we could get away with a single `users` table:

_user table_:

| column name | type | notes |
| --- | --- | --- |
| id | integer |  |
| email | string |  |
| username | string |  |
| password | string |  |
| date_create | datetime |  |
| last_login | datetime |  |
| address_1 | string |  |
| address_2 | string |  |
| state | integer | foreign key to state table? |
| country | integer | foreign key to country table? |

as far as integrations with facebook and other apps go, don't over-engineer this thing right now. we could always create a separate table for tracking facebook user ids and stuff like that:

_third_party_account table_ (or something like that)

| column name | type | notes |
| --- | --- | --- |
| id | integer |  |
| user_id | integer | foreign key to user |
| provider | enum? |  |
| oauth_token | string |  |
| refresh_token | string |  |
| foreign_id | string |  |

**Comment by cpb2948** [comment]
Sure i can change it. It doesn't really matter to me much. Its just how it came to mind when i was creating the tables. We have it separated at work as well. Ill make a task to change that over, ill update the migrations and database seeds

**Comment by cpb2948** [comment]
as well as any of the existing code we have that uses the account information

**Comment by dadleyy** [comment]
alrighty. I'm whippin up the clientside foundation and will push soon. pretty experimental stuff.

**Comment by cpb2948** [comment]
Do you know of any like design tools or software? Something where we can generate how we want each page to look like.

**Comment by dadleyy** [comment]
nope. I winged it on loftili and it came out alright.

**Comment by cpb2948** [comment]
word

**Comment by cpb2948** [comment]
Do you have to do anything special for the :shipit emojii thing?

**Pull request merged**
